[workspace]
members = [
    ".",
]

[package]
name = "mavsdk-rust-ffi"
version = "3.13.0"
edition = "2024"
license = "BSD-3-Clause"

[dependencies]
autocxx = "0.30.0"
cxx = "1.0.78"
libc = "0.2.180"
tokio = {version = "1.49.0", features = ["full"]}

[build-dependencies]
autocxx-build = { git = "https://github.com/zeroy0410/autocxx.git", branch = "fix_issue_1488" } #PR: https://github.com/google/autocxx/pull/1490, without this patch, many plugins do not build due to issues of generating bindings for code that returns std::string
cmake = "0.1.54"
miette = { version = "5", features = ["fancy"] }
glob = { version = "0.3.2" }
