// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see
// https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/shell/shell.proto)

#include <iomanip>

#include "plugins/shell/shell.h"
#include "shell_impl.h"

namespace mavsdk {

Shell::Shell(std::shared_ptr<System> system)
    : PluginBase(), _impl{std::make_unique<ShellImpl>(system)} {}

Shell::~Shell() {}

Shell::Result Shell::send(std::string command) const {
  return _impl->send(command);
}

uintptr_t Shell::subscribe_receive(uintptr_t cb_ptr, uintptr_t user_data) {
  using RawCallbackType = void (*)(uintptr_t, std::string);
  auto callback = reinterpret_cast<RawCallbackType>(cb_ptr);
  if (!callback) {
    return 0;
  }

  Shell::ReceiveHandle handle =
      _impl->subscribe_receive([callback, user_data](auto &&...args) {
        callback(user_data, std::forward<decltype(args)>(args)...);
      });
  auto *handle_ptr = new Shell::ReceiveHandle(handle);
  return reinterpret_cast<uintptr_t>(handle_ptr);
}

void Shell::unsubscribe_receive(uintptr_t handle_ptr) {
  if (!handle_ptr) {
    return;
  }
  auto handle = reinterpret_cast<ReceiveHandle *>(handle_ptr);
  _impl->unsubscribe_receive(*handle);
  delete handle;
}

Shell::ReceiveHandle Shell::subscribe_receive(const ReceiveCallback &callback) {
  return _impl->subscribe_receive(callback);
}

void Shell::unsubscribe_receive(ReceiveHandle handle) {
  _impl->unsubscribe_receive(handle);
}

std::ostream &operator<<(std::ostream &str, Shell::Result const &result) {
  switch (result) {
  case Shell::Result::Unknown:
    return str << "Unknown";
  case Shell::Result::Success:
    return str << "Success";
  case Shell::Result::NoSystem:
    return str << "No System";
  case Shell::Result::ConnectionError:
    return str << "Connection Error";
  case Shell::Result::NoResponse:
    return str << "No Response";
  case Shell::Result::Busy:
    return str << "Busy";
  default:
    return str << "Unknown";
  }
}

} // namespace mavsdk