use crate::ir::{StructIR};
use std::io::Write;

// Convert module name to PascalCase
// Used for naming the namespaces in C++ and the Getters struct in Rust
fn module_to_pascal_case(module: &str) -> String {
    module
        .split('_')
        .map(|s| {
            let mut c = s.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect()
}

pub fn write_rust_struct(w: &mut impl Write, module: &str, s: &StructIR) -> std::io::Result<()> {
    writeln!(w, "impl {} {{", s.semantic_name)?;

    for field in &s.fields {
        if field.rust_type_name.is_empty() {
            continue;
        }

        let prefix = if field.is_pod { "" } else { "&" };
        let reserved_keywords = [
            "type", "match", "ref", "self", "super", "crate", "mod", "fn", "let", "mut",
        ];

        let field_name = if reserved_keywords.contains(&field.name.as_str()) {
            format!("r#{}", field.name)
        } else {
            field.name.clone()
        };

        writeln!(w, "    pub fn {}(&self) -> {}{} {{", field_name, prefix, field.rust_type_name)?;
        writeln!(w, "        {}::{}Getters::{}::get_{}(&self)", module, module_to_pascal_case(module), s.name, field.name)?;
        writeln!(w, "    }}")?;
    }

    writeln!(w, "}}")?;
    Ok(())
}

pub fn write_cpp_struct(w: &mut impl Write, s: &StructIR) -> std::io::Result<()> {
    writeln!(w, "    struct {} {{", s.name)?;
    for field in &s.fields {
        let ret_prefix = if field.is_pod {
            format!("static {}", field.cpp_type_name)
        } else {
            format!("static const {}&", field.cpp_type_name)
        };

        writeln!(w, "        {} get_{}(const {}& instance) {{", ret_prefix, field.name, s.semantic_name_cpp)?;
        writeln!(w, "            return instance.{};", field.name)?;
        writeln!(w, "        }}")?;
    }
    writeln!(w, "    }};")?;
    Ok(())
}

// Generate rust file with getters for a module
pub fn generate_rust_file(path: &std::path::Path, module: &str, structs: &[StructIR]) -> std::io::Result<()> {
    let mut file = std::fs::File::create(path)?;
    
    // Write File Header
    writeln!(file, "// WARNING: THIS FILE IS AUTOGENERATED! Do not edit.")?;
    writeln!(file, "use cxx::*;")?;
    //writeln!(file, "use libc::*;")?;
    writeln!(file, "")?;

    // Write each struct
    for s in structs {
        write_rust_struct(&mut file, module, s)?;
        writeln!(file, "")?; // Extra newline for readability
    }

    Ok(())
}

// Generate cpp file with getters for a module
pub fn generate_cpp_file(path: &std::path::Path, module: &str, structs: &[StructIR]) -> std::io::Result<()> {
    let mut file = std::fs::File::create(path)?;
    
    // Write File Header
    writeln!(file, "// WARNING: THIS FILE IS AUTOGENERATED! Do not edit.")?;
    writeln!(file, "#pragma once")?;
    writeln!(file, "")?;

    writeln!(file, "namespace {}Getters {{", module_to_pascal_case(module))?;

    // Write each struct
    for s in structs {
        write_cpp_struct(&mut file, s)?;
    }

    writeln!(file, "}}")?;
    Ok(())
}